image: node:13

# before_script:
#   - chmod 600 $SSH_PRIVATE_KEY

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  - deploy

build_parcel_master:
  stage: build
  script:
    - npm install
    - npm install -g parcel-bundler
    - node -v
    - parcel build ./src/index.html --public-url ./
  artifacts:
    expire_in: 20 mins
    paths:
      - dist
  only: 
    - master

deploy_master:
  stage: deploy
  variables:
    SERVEUR: "quentin@85.208.144.169"
    CHEMIN: "/var/www/dev/dfl-dashboard/dist/"
  script:
    - which rsync || ( apt update -y && apt install rsync -y )
    - ls -la
    - cat $SSH_PRIVATE_KEY
    - /usr/bin/rsync -rKzlvhq -e "ssh -i $SSH_PRIVATE_KEY" --stats --delete-after --ignore-errors --force --itemize-changes ./dist/ ${SERVEUR}:${CHEMIN}. --exclude-from="exclude.build"
  only:
    - master