image: node:13

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  - deploy

build_parcel_master:
  stage: build
  script:
    - npm install
    - npm install -g parcel-bundler
    - node -v
    - parcel build ./src/index.html --public-url ./
  artifacts:
    expire_in: 20 mins
    paths:
      - dist
  only: 
    - master

deploy_master:
  stage: deploy
  variables:
    SERVEUR: "quentin@85.208.144.169"
    CHEMIN: "/var/www/dev/dfl-dashboard/dist/"
  script:
    - which rsync || ( apt update -y && apt install rsync -y )
    - ls -la
    - ssh -p22 quentin@85.208.144.169
    - mv ./dist /var/www/dev/dfl-dashboard/dist
  only:
    - master